### PR TITLE
[redesign] Trezor views

### PR DESCRIPTION
**Pull request by bgptr**
Toward issue  #3297
Requires https://github.com/decred/pi-ui/pull/410 (merged)

This diff implements the updated Trezor views in #3297. 
On Wallet Selection view  - as an only change -  a `Create a Trezor-backed Wallet` button has been added. 
Tested on a physical Trezor One device and Trezor Modal T simulator.
Also added automated tests for the trezor views.

Screenshots:

create-trezor-view
create-trezor-view-closed-device-setup
create-trezor-view-opened-device-setup
no-device-view
trezor-settings-1
pin-modal

### CODE REVIEW

**Comment by alexlyp** [comment]
@matheusd When you have some time it would be great if you could take a look at this diff.  Changes and code looks solid but I don't currently have the ability to fully test all of the Trezor bits.

**Review by matheusd — COMMENTED** [review]
LGTM (tested on model one and model T emulators)

**Review by matheusd — APPROVED** [review]
LGTM (tested on model one and model T emulators)

Small nits, that are not show stoppers:
  - Sending a tx doesn't seem to be triggering notifications anymore (not sure it's related to this PR)
  - When restoring a model one and typing the seed words, the input focus is lost between words, so you need to click again in the input box after every word

**Comment by alexlyp** [comment]
Opened a new issue for these nits in #3835

**Pull request merged**
