### PR TITLE
Start spv mode

### PR DESCRIPTION
**Pull request by vctt94**
This PR starts #1243. 

It adds SPV to config and remove the following functionalities when in spv.

- purchase ticket 
- ticket auto buyer
- vote

### CODE REVIEW

**Comment by matheusd** [comment]
AFAIK, it's not that you won't be able to purchase tickets, you just won't be able to use the ticketbuyer ("automatic buyer" in decrediton) for that. 

Also, the voting in decrediton is used to set vote choices in the pool, **not** for a solo voter, so those actions also won't be affected by the SPV work.

**Comment by jrick** [comment]
Buying tickets is problematic for SPV wallets because they won't know the ticket price at the beginning of a new interval.  The ticket price (sdiff) in the block header is the stake difficulty to buy tickets in that block, not the next block.

**Comment by matheusd** [comment]
Right, I don't know all details how SPV is being implemented, but doesn't the wallet have all block headers, implying it knows the current block height? If so, we can just prevent the wallet from buying tickets near the end of the sdiff change window and wait until at least one (or better yet, a couple of blocks to protect against reorg) have been received.

**Comment by matheusd** [comment]
Don't really need to change dcrwallet for that. You only need to get the `currentBlockHeight`, and check if it is near the edge of the an sdiff change (basically `currentBlockHeight mod WorkDiffWindowSize`).

That might actually be something interesting to display on decrediton's purchase ticket screen (how many blocks until an sdiff change).

**Comment by dajohi** [comment]
@vctt94 can you rebase?

**Comment by vctt94** [comment]
rebased

**Pull request merged**
