### PR TITLE
[css modules] ditch `Help.less` & cleanup

### PR DESCRIPTION
**Pull request by amassarwi**
This diff splits old `styles/Help.less` file into two css modules: `components/views/SettingsPage/LinksTab/LinksTab.module.css` & `components/buttons/HelpLink/HelpLink.module.css` and cleans up few old not used `.svg` icons.

One more step towards #2439

### CODE REVIEW

**Review by jholdstock — APPROVED** [review]
Code lgtm and works well

**Review by vctt94 — APPROVED** [review]
LGTM. 

I liked the idea of using an icon props for the help link.

I think we can do the same with our `txHistory` component, for showing txs icons, what do you think?

**Comment by amassarwi** [comment]
@vctt94 agreed mate, will do in a separate PR.

**Comment by vctt94** [comment]
I think we can work on that after getting #3012 in

**Comment by amassarwi** [comment]
@vctt94 sounds good to me 👍

**Pull request merged**
