### PR TITLE
List UTXO’s modal

### LINKED ISSUE #3281: List UTXO’s view / modal update
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

Basically we left the link at the same place as before. Just changed the way of displaying the list. Now it is within a modal.
image

**An implementation right now:**
image

**An updated design:**
image

**An example with scroll bar and maximum practical height for the modal, in case there's more than fits the view:**
image

### PR DESCRIPTION
**Pull request by bgptr**
Closes #3281 and #3321

### CODE REVIEW

**Comment by alexlyp** [comment]
looks mostly good.  Only issue I notice is in dark mode the font colors look a little off and the top bar (that has UTXO and Value) is not colored correctly.

**Comment by alexlyp** [comment]
I also think it's worth matching the minimum spacing on the top and bottom of the modal to match the sides.  Seems a little tight on the top and bottom, 20 px seems like a good amount of margin/padding there

**Comment by bgptr** [comment]
@alexlyp Thanks for the review. I've improved the colors in dark mode, but I am not sure about your margin/padding comment. Could you attach a screenshot?

**Comment by alexlyp** [comment]
Can't unfortunately.  But basically I'm see the top and bottom of the modal come too close to the very edge of the electron window.  Feel like that space should be wider.

**Comment by bgptr** [comment]
@alexlyp Now I see what you mean. I've improved the spacing.

**Comment by alexlyp** [comment]
Ah much better thanks for the update @bgptr

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
