### PR TITLE
[transaction] `self` & `mixed` icons

### LINKED ISSUE #3019: [privacy] Mixed tx not showing `is mix` indicator
As noted by @vctt94 some mixed tx(s) not showing mixed indicator.

image

This one to be more specific: https://testnet.decred.org/tx/d94b5d25e6b94aedc50ea2a29b17ce80d77d27d18cc4c9945edefce904e11d46

### PR DESCRIPTION
**Pull request by amassarwi**
This diff replaces `is mixed` text indication with new icon as specified in the specs for mixed transactions.
In addition, it defines new type - `self` transaction & adds it's icon.

While parsing wallet transactions we mark a tx as `self` transaction when:
```
// If we find in the transaction credits list a self credited account which isn't a change output
// & tx has one or more wallet inputs & no non-wallet outputs we consider
// the transaction as self transaction
``` 

Specs:

image

---

Part of #2964 
Closes #3019

### CODE REVIEW

**Review by vctt94 — COMMENTED** [review]
Thanks for this PR amass, looking good! 

I think it would be good if we add tooltips on the icons, because it can be confusing now with so many icons. 

Also, when clicking on the tx, it has the old icon, can we change that?

**Comment by jholdstock** [comment]
Tooltip is definitely a good idea!

**Comment by vctt94** [comment]
Also, it looks like one of my mixed txs is showing as a `sent` tx: 

image

This one to be more specific: https://testnet.decred.org/tx/d94b5d25e6b94aedc50ea2a29b17ce80d77d27d18cc4c9945edefce904e11d46

**Comment by amassarwi** [comment]
Thanks for the review guys, can do tooltip and add the icon in the details page.

Regarding the `sent` tx i saw that and was able to reproduce on master (this tx won't have current `is mix` text indicator) it's related to the `isMix` flag logic, maybe we should fix that in a different PR ?

**Comment by amassarwi** [comment]
Will fix https://github.com/decred/decrediton/issues/3019 and then finalized this one

**Review by vctt94 — APPROVED** [review]
LGTM. Although the transaction mentioned is still showing as a `sent` tx, but I believe we can have an issue for that and fix in a further PR

**Pull request merged**
