### PR TITLE
Configured VSP view

### PR DESCRIPTION
**Pull request by guilhermemntt**
Closes https://github.com/decred/decrediton/issues/2305.

### CODE REVIEW

**Comment by guilhermemntt** [comment]
I removed the legacy code `` .less`` that doesn't break other component styles across the ticket views. The "x" button in the specs does intends to remove the configured VSP, but since "x" is commonly used to close current views or return to previous views in Decrediton, we'll wait a decision on what to do in this case.

**Comment by vctt94** [comment]
@linnutee will update the issue with the properly icon

**Comment by guilhermemntt** [comment]
The remove VSP icon has been updated.

**Comment by guilhermemntt** [comment]
Rebased.

**Comment by alexlyp** [comment]
Needs a rebase.

**Comment by guilhermemntt** [comment]
Rebased.

**Pull request merged**
