### PR TITLE
Fix misc lint errors

### PR DESCRIPTION
**Pull request by StabbarN**
Running eslint gives:

```
.../decrediton/scripts/aliasDefaultMessage.js
  13:5   error  Expected indentation of 2 spaces but found 4    indent
  13:5   error  Strings must use doublequote                    quotes
  16:35  error  Strings must use doublequote                    quotes
  20:5   error  Expected indentation of 2 spaces but found 4    indent
  21:9   error  Expected indentation of 6 spaces but found 8    indent
  22:13  error  Expected indentation of 10 spaces but found 12  Vindent
  25:9   error  Expected indentation of 6 spaces but found 8    indent
  28:5   error  Expected indentation of 2 spaces but found 4    indent
  29:9   error  Expected indentation of 6 spaces but found 8    indent
  29:41  error  Strings must use doublequote                    quotes
  32:5   error  Expected indentation of 2 spaces but found 4    indent
  33:9   error  Expected indentation of 6 spaces but found 8    indent
  34:9   error  Expected indentation of 6 spaces but found 8    indent
  35:13  error  Expected indentation of 10 spaces but found 12  indent
  38:9   error  Expected indentation of 6 spaces but found 8    indent
  39:13  error  Strings must use doublequote                    quotes
  43:5   error  Expected indentation of 2 spaces but found 4    indent
  44:9   error  Expected indentation of 6 spaces but found 8    indent
  45:13  error  Expected indentation of 10 spaces but found 12  indent
  48:9   error  Expected indentation of 6 spaces but found 8    indent
  51:5   error  Expected indentation of 2 spaces but found 4    indent
  52:9   error  Expected indentation of 6 spaces but found 8    indent
  52:50  error  'valuePath' is defined but never used           no-unused-vars
  53:13  error  Expected indentation of 10 spaces but found 12  indent
  55:13  error  Expected indentation of 10 spaces but found 12  indent
  56:17  error  Expected indentation of 14 spaces but found 16  indent
  59:13  error  Expected indentation of 10 spaces but found 12  indent
  63:5   error  Expected indentation of 2 spaces but found 4    indent
  64:9   error  Expected indentation of 6 spaces but found 8    indent
  65:13  error  Expected indentation of 10 spaces but found 12  indent
  66:17  error  Expected indentation of 14 spaces but found 16  indent
  66:24  error  'file' is assigned a value but never used       no-unused-vars
  67:17  error  Expected indentation of 14 spaces but found 16  indent
  68:17  error  Expected indentation of 14 spaces but found 16  indent
  68:39  error  Strings must use doublequote                    quotes
  70:17  error  Expected indentation of 14 spaces but found 16  indent
  71:21  error  Expected indentation of 18 spaces but found 20  indent
  71:49  error  Strings must use doublequote                    quotes
  74:21  error  Expected indentation of 18 spaces but found 20  indent
  76:29  error  Expected indentation of 26 spaces but found 28  indent
  76:38  error  Strings must use doublequote                    quotes
  77:29  error  Expected indentation of 26 spaces but found 28  indent
  77:38  error  Strings must use doublequote                    quotes
  81:21  error  Expected indentation of 18 spaces but found 20  indent
  82:25  error  Expected indentation of 22 spaces but found 24  indent
  88:6   error  Missing semicolon                               semi

.../decrediton/scripts/prepareUntranslated.js
  2:36  error  Strings must use doublequote  quotes

✖ 47 problems (47 errors, 0 warnings)
```
This PR corrects that.

### CODE REVIEW

**Comment by matheusd** [comment]
What command line are you using to get these errors? We usually run `yarn lint` which is checking only `./app`.

**Comment by StabbarN** [comment]
Oh, I should have used `yarn lint`, but why isn't the folder `scripts` included? 

I used eslint directly, i.e. `./node_modules/.bin/eslint .`.

**Comment by matheusd** [comment]
There are just a couple of aux scripts there, so never critical. 

Could you amend your PR to include the scripts folder on `yarn lint`?

**Comment by StabbarN** [comment]
@matheusd scripts folder added.

**Pull request merged**
