### PR TITLE
Finishing overview cards style

### LINKED ISSUE #1191: Visual Design Fix: Ticket structure
screen shot 2018-02-21 at 18 23 47

Visual Design for the individual Tickets in` My Tickets` view needs some fine tuning, please refer to the last specs: https://xd.adobe.com/spec/b52c9c2e-1f77-4881-81d6-1b417595a6a3/

To check: 
- Sizing (kebab menu) 
- Reward icons / timelock 
- Hovers
- Shadows described in #1190  

Icons: 
[decrediton-ticket-icons.zip](https://github.com/decred/decrediton/files/1744797/decrediton-ticket-icons.zip)

### PR DESCRIPTION
**Pull request by vctt94**
fixes #1191 

Right now we are using txType to show tickets information on transactions history page. It only shows voted, ticket, revoked. I think would be nice using ticket status so we can have more ticket information on history transactions page, so I added this ToDo here, but I am not sure if it is necessary.

https://github.com/decred/decrediton/pull/1186/files#diff-5a4b88f9ad16f90e531c84ec6dad3d69R21

Maybe we can have an issue for showing status information like at overview page. Any thoughts?

### CODE REVIEW

**Comment by alexlyp** [comment]
I'm getting a ticketPrice of undefined error when I try to load into the Overview screen.

**Comment by vctt94** [comment]
I got this error once, but I can not reproduce it again. How do you get it?

**Comment by alexlyp** [comment]
Just a normal load.

**Comment by alexlyp** [comment]
I'll keep trying to hit that issue again, not sure the cause.  

In the meantime, I'm seeing the rows be too tall which causes 6 to run off the screen.  Change the default to 5 to load if you can't reduce the height.

**Comment by vctt94** [comment]
Okay, I will keep an eye to see if it happens to me as well. I thought it could be decrediton starting before the tickets, but the tickets are started on the start wallet step.

**Comment by matheusd** [comment]
I'm getting a "Cannot Read Property 0 of null" when hovering the mouse over the charts.

**Comment by alexlyp** [comment]
@vctt94 can you add tooltips to the lock, reward, ticket price like it is on the My Tickets screen?

**Pull request merged**
