### PR TITLE
Translating decrediton

### LINKED ISSUE #572: Add internationalization support
Decrediton is lacking support for internationalized messages; currently everything is hardcoded in English. Either we should derive the user's language from the OS through Electron (if that's possible and the translations are available) and display that automatically, or provide an option on the Settings page which displays all available translations and lets the user dynamically switch.

We can most likely use this webpack plugin: https://github.com/webpack-contrib/i18n-webpack-plugin

### PR DESCRIPTION
**Pull request by matheusd**
Fixes #572.

Opening PR for discussion. Should be close to final. After this is approved and merged I'll work with @peterzen and the rest of the translation managers to get translation started.

There's a readme inside the `/app/i18n` dir for general instructions and templates for adding translated items.

### CODE REVIEW

**Comment by matheusd** [comment]
I commented the tests because we'll need to rework how to unit test with translation.

**Comment by alexlyp** [comment]
Looks great to me, but I want to get everyone's input on this before we proceed with this i18n impl.

**Comment by peterzen** [comment]
Looks good to me as well.

**Comment by matheusd** [comment]
Free to merge when possible.

**Pull request merged**
