### PR TITLE
Add BIP-0021 support

### LINKED ISSUE #2365: Add BIP-0021 support
Under the Transactions > Receive tab it would be good to have a place to specify an amount and have the QR code update to reflect that based on BIP-0021.

https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

### PR DESCRIPTION
**Pull request by bgptr**
closes #2365

### CODE REVIEW

**Comment by bgptr** [comment]
@matheusd: thank you for your review, I agree with you. In regards to the mobile wallets, I  suppose the upcoming builds will support it. The related PR is merged in dcrandroid and there is a related open PR in dcrios.

**Comment by matheusd** [comment]
Can you link to the relevant PRs here?

**Comment by bgptr** [comment]
@matheusd sure. decred/dcrandroid#411 and raedahgroup/dcrios#581

**Comment by matheusd** [comment]
Thanks! Makes sense to have this in decrediton then.

**Pull request merged**
