### PR TITLE
Add infinite scroll on transaction list

### LINKED ISSUE #930: Infinite scrolling on transaction history
To be done after #875.

Implement infinite scrolling and other UI/UX improvements on the transaction history tab.

### PR DESCRIPTION
**Pull request by matheusd**
This implements infinite scrolling of the transaction list page using the https://github.com/CassetteRocks/react-infinite-scroller component.

I've used a small stakey bouncing as indicator during transaction loading. That indicator (or a more generic version) may be used as basis for #920.

Fix #930.

### CODE REVIEW

**Comment by alexlyp** [comment]
Nice really like the UX for this, huge improvement.

For the stakey loading div, I was thinking we could avoid showing unless it is taking longer than some amount of time, like 1 sec.  I only rarely see it appear at the bottom and typically it just flashes and goes away.  Not really sure what the proper way to handle this is.  Maybe put in a slight artificial delay?

**Comment by matheusd** [comment]
Good idea. I can also increase the distance from the bottom where the loading is triggered (so you usually never reach the end of the list while scrolling)

**Comment by alexlyp** [comment]
Ah yah I like that idea.  Something to give a little more feedback would be nice.

**Comment by matheusd** [comment]
Feedback to what operation? The loading? Something in addition to the stakey indicator?

**Comment by alexlyp** [comment]
Ah let me be a bit more clear. 

The way I see it goes 2 ways: either we give more feedback and slow down if the height is near the bottom or up the height and it becomes essentially transparent to the user that it is getting more transactions to show.  In the 2nd option, no feedback is required.

**Comment by matheusd** [comment]
Right. Just pushed one increasing the height, as that is easiest. See if that is enough.

**Comment by alexlyp** [comment]
Feels really good now.

**Pull request merged**
