### PR TITLE
Dark Mode: Settings selection

### PR DESCRIPTION
**Pull request by bgptr**
Solving(#2093)
Ref to master issue: #2089

Dark mode toggle button replaced according to design.

### CODE REVIEW

**Comment by bgptr** [comment]
Thanks for the review. 

Do you mean the navigation bar? 
I would like to skin it, but it's in the issue (#2090) and I didn't want to mix the issues.

**Comment by vctt94** [comment]
okay, that's fine. 

There is also another issue I noticed. If you close decrediton it returns to the light theme. You should save this information at the `config.json` file so it can be persisted.

**Comment by bgptr** [comment]
In my implementation, after you choose the theme, you have to click the `Save` button to make the information persistent. 
Of course, it can be saved immediately if you want.

**Comment by vctt94** [comment]
Oh, my bad. I haven't seen the save button, but it is our current behavior at settings. 

If you could reset your commits to cb993b7aa020267ae56bd76dd6d4204b14c53e6f would be good, so we do not have different behaviors at our settings changes. 

Otherwise LGTM.

**Comment by bgptr** [comment]
No problem. I reset the commit.

**Pull request merged**
