### PR TITLE
clean useGetStarted console.log

### PR DESCRIPTION
**Pull request by amassarwi**

### CODE REVIEW

**Review by vctt94 — COMMENTED** [review]
Hey amass, thanks for this PR.

Can you make me a favor and also remove some logs from `syncVSPTickets` at control.js? I forgot about them and they shouldn't be there

**Comment by amassarwi** [comment]
@vctt94 Anytime mate - done.

**Review by vctt94 — APPROVED** [review]
Thanks! 

É nóis (as we say in brazil)

**Comment by amassarwi** [comment]
🇧🇷

**Pull request merged**
