### PR TITLE
Enable eslint's new indent rule

### PR DESCRIPTION
**Pull request by StabbarN**
Enforces consistent indentation.

After change of `.eslintrc.js` I executed `node_modules/.bin/eslint app scripts --fix`. 

The changes in this PR can easily be checked by making a new branch, update the .estlintrc, execute the eslint with `--fix` and then run `git diff eslint-new-indent`.

For more info see https://eslint.org/docs/rules/indent

### CODE REVIEW

**Comment by alexlyp** [comment]
Looks good, just need to rerun this on master due to conflicts.  

Before I merge I need confirmation from @matheusd and @vctt94 that this will not cause major conflict issues with any in-progress branches.

**Comment by matheusd** [comment]
Apart from #1136, I'm not working on anything big enough to be affected by this change at this moment.

Other stuff I'm working on I can fix the lint if this rule change is accepted.

IMO it's good to have this rule active.

**Comment by vctt94** [comment]
I agree with Matheus, and I do not have big branchs too.

**Comment by alexlyp** [comment]
@StabbarN plz redo this PR

**Comment by StabbarN** [comment]
@alexlyp you mean rebase? Or redo in what way?

**Comment by alexlyp** [comment]
Well there are conflicts you need to resolve.  Resolve them how ever you want

**Comment by StabbarN** [comment]
@alexlyp It's been done.

**Pull request merged**
