### PR TITLE
Improved `running in background` animation.

### LINKED ISSUE #3243: Differnet `mixer is on` animation.
@alexlyp disabled lately the side bar animation we used to have when autobuyers or mixer were on
because of performance issues - see https://github.com/decred/decrediton/pull/3231#discussion_r577146043

We need new animation, would it make sense to use the same animation we use in the privacy page ? 🤔

### PR DESCRIPTION
**Pull request by amass01**
As discussed in https://github.com/decred/decrediton/issues/3243#issuecomment-825651503:
This uses the new animation suggested in #3243 - shows the indicator next to the `Privacy and Security` menu item when the mixer is on, but next to the `Staking` when the ticket autobuyer is on or there is a ticket purchase attempt.

Closes #3243.

### CODE REVIEW

**Comment by amassarwi** [comment]
Old running in background tooltip test is failing.

**Comment by alexlyp** [comment]
Hrm I find this animation to be a bit too subtle on Dark mode.  Plus without the tooltip i'm not sure it's clear that it indicates why it's there.

**Comment by amassarwi** [comment]
@alexlyp I'll add the changes to `pi-ui` to make it possible to pass the `Tooltip` as menu item and see how it goes.

**Comment by alexlyp** [comment]
Closing this PR due outdatedness.

**Pull request closed without merging**
