### PR TITLE
[LN] watchtowers

### PR DESCRIPTION
**Pull request by fguisso**
add Watchtowers support:
image

### CODE REVIEW

**Review by victorgcramos — COMMENTED** [review]
This code is awesome! Very clean and declarative. Good job!

**Review by matheusd — COMMENTED** [review]
Needs an option to remove a watchtower

**Review by matheusd — APPROVED** [review]
Working nicely now!

**Review by vctt94 — APPROVED** [review]
The issue I found is fixed! LGTM

**Pull request merged**
