### PR TITLE
Fix `Go to Voting Dashboard` button

### LINKED ISSUE #3494: Consensus changes: `Go to Voting Dashbaord` leading to proposals site.
image

### PR DESCRIPTION
**Pull request by bgptr**
Closes #3494

### CODE REVIEW

**Comment by jholdstock** [comment]
Switch for testnet?  https://voting.decred.org/testnet

**Comment by bgptr** [comment]
@jholdstock Thanks for testing.
I introduced a new `ExternalButton` component, which is similar to `ExternalLink` and can handle testnet links.
I fixed the `proposals.decred.org` link in the header of `Proposals` view too.

**Review by matheusd — APPROVED** [review]

**Review by amassarwi — COMMENTED** [review]
we do we need both ExternalButton and PiLink ?

**Comment by bgptr** [comment]
Yeah, they are similar. I suppose `PoliteiaLink` is meant to be used for `proposals.decred.org/*` URLs. It receives a `path` prop and builds the testnet/mainnet URL: `https://${isTestnet ? "test-proposals" : "proposals"}.decred.org${path || ""}`. 
This URL building logic does not fit for https://voting.decred.org/testnet format and I wanted a more generic component, like the `ExternalLink`.

**Comment by amassarwi** [comment]
@bgpt I see, makes sense.

**Pull request merged**
