### PR TITLE
History tab remembers its scroll position

### PR DESCRIPTION
**Pull request by bgptr**
closes (#784)

### CODE REVIEW

**Comment by bgptr** [comment]
It is absolutely icky. Maybe the scroll position saving and restoring could be working, but then the scroll jumping would be odd IMHO. Do you have another solution idea?

No specific reason using `useModalForDetails` just didn't want to modify another part of the application. I can revert it in no time if you see it necessary.

**Comment by matheusd** [comment]
Yeah, I think the parametrization can be left out, I don't see us using two different views for transaction details.

**Comment by bgptr** [comment]
Ok, I reverted it.

**Comment by bgptr** [comment]
Thanks! I've fixed it and also removed the fixed positioning.

**Pull request merged**
