### PR TITLE
Fix dropdown z-index on Tx History view

### LINKED ISSUE #2708: Tx History: Pending tx ellipsis drawn over tx type menu
The animated ellipsis shown next to an unmined transaction in the transaction history list is rendered over the dropdown transaction type selection menu - I would expect the menu to be drawn on top

Peek 2020-10-12 09-42

### PR DESCRIPTION
**Pull request by bgptr**
Closes #2708

### CODE REVIEW

**Review by victorgcramos — APPROVED** [review]
Working as expected. LGTM!

**Review by amassarwi — APPROVED** [review]
ACK, I suggest we drop a comment to explain why z-index:2 or something.

**Comment by bgptr** [comment]
Thank you for your reviews. @amassarwi I added a comment as you suggested. Actually z-index:1 is enough. Thanks!

**Review by vctt94 — APPROVED** [review]
LGTM

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
