### PR TITLE
Global colors fix

### PR DESCRIPTION
**Pull request by peterzen**
Fix for #1997 

The problem was that global `color:` was applied on `body.decrediton` but the `--input-color-default` variable was defined on a sub-element so the value wasn't accessible on `body`.  (The commit that caused this: https://github.com/decred/decrediton/commit/a2a61aecf4bf49258f04fc5b1947aff683d3b489#diff-5eadd9daae27235a982192150aff5958

This PR fixes the issue by moving the style onto a sub-element, and I did a slight refactoring as well to move some global styles from `Global.less` into `main.less` so that these top-level classes reside in one file.

### CODE REVIEW

**Comment by alexlyp** [comment]
Mmm looks good overall.

Why did you change the base branch?  Typically the way I've done it is to merge changes into master then I cherry pick on the release branch.  Though I believe we may have missed the window.  The full release is in the chamber and aiming for full release tomorrow.

**Comment by peterzen** [comment]
Yeah, I wasn't sure whether the window was still open or not, so opened another PR targeting 1.4: https://github.com/decred/decrediton/pull/2007  

Attn @vctt94

**Comment by peterzen** [comment]
If the window is definitely gone I'll rebase this back onto `master`.

**Comment by alexlyp** [comment]
Needs a rebase.

**Comment by peterzen** [comment]
Rebase done

**Pull request merged**
