### PR TITLE
Add rpc version mismatch alert

### LINKED ISSUE #769: No error given when dcrwallet version is not appropriate
There is a dcrwallet rpc version check on start up to ensure that the expected built api.proto is being used on a valid verison of dcrwallet bin.  When the error is tripped you can see `VERSION_NOT_VALID` on the console, but decrediton just sits at the Check Wallet Loading screen.

### PR DESCRIPTION
**Pull request by matheusd**
Fix #769

### CODE REVIEW

**Comment by alexlyp** [comment]
So the screen looks good and properly catches the rpc version mismatch.

But I'm thinking the text on the page is a little off, mostly due to the version shown on the About screen is the app version and not the rpc version.  Maybe we can add the rpc version there for wallet  as well?

`dcrwallet {app version} (rpc version {rpc version})`

**Comment by matheusd** [comment]
Do you want me to remove the version from the initial error screen and leave it only on the about page? Or no problem leaving it in the two?

**Comment by alexlyp** [comment]
I think having it in both places is fine

**Comment by matheusd** [comment]
Preview
screenshot_2017-10-19_15-05-44

**Comment by alexlyp** [comment]
cool looks good.  I have an open issue for 1.1.2 that requests some better styling for the about screen so we can shift/adjust layout later.

**Comment by matheusd** [comment]
Feels kinda hacky the way I had to extract the data from the react hierarchy to pass to the about page, but since it (the about page) is outside of the main app store, I couldn't think of a simpler way to do that.

**Pull request merged**
