### PR TITLE
Migrate from grpc to grpc-js.

### PR DESCRIPTION
**Pull request by jholdstock**
- Change app dependency from `"grpc"` to `"@grpc-js"`.
- Regenerate all proto files with `generate_package_definition` flag.
- Remove unused files `annotations_pb.js` and `http_pb.js`, and don't regenerate them `regen.sh`.
- In the `regen.sh` for LN protos, use protoc installed locally in node_modules rather than one provided by the system.

Some nice stats...

|                                | Before this PR  | After   |
|--------------------------------|-----------------|---------|
|`yarn` time                     | 248s            |  20s    |
|`yarn package` time             | 14m 41s         |  8m 43s |
|`decrediton-v1.6.0.tar.gz` size | 260MB           |  210MB  |

### CODE REVIEW

**Comment by jholdstock** [comment]
I've converted this to a draft because it should not be merged right now.

- Retrying mechanism from #2935 should be merged first
- A change is needed in dcrlnd. A small sleep before shutting down the unlock service prevents grpc-js throwing `Error: 14 UNAVAILABLE: Connection dropped`

**Comment by xaur** [comment]
> decrediton-v1.6.0.tar.gz size 	260MB 	210MB

Epic, thank you!

**Comment by alexlyp** [comment]
@matheusd @jholdstock did the needed changes in dcrlnd happen?  Was hoping to get this in soon so we could include in the upcoming patch release

**Comment by jholdstock** [comment]
Not merged yet decred/dcrlnd#122

**Comment by jholdstock** [comment]
Rebased and bumped `grpc/grpc-js` from `1.2.0` to `1.2.5` (latest)

**Comment by matheusd** [comment]
I hadn't merged the dcrlnd one because we weren't going to merge this for 1.6, but since that's now released I'll merge the dcrlnd change

**Comment by alexlyp** [comment]
Ah great thanks.  Aiming to add this to the 1.6.1 patch release I think.

**Review by matheusd — APPROVED** [review]
Tested with the current master dcrlnd

**Pull request merged**
