### PR TITLE
Responsive restore seed

### PR DESCRIPTION
**Pull request by vctt94**
This PR starts #2058 and I am doing some clean up on the code, as well. 

It is not finished because it is still lefting the trezor option on the responsive mode, but when addressed, I can finish it.

### CODE REVIEW

**Comment by matheusd** [comment]
The words/hex toggle seems to get left out of the screen on smaller widths.

**Comment by vctt94** [comment]
fixed.

Also fixed some stuff I left behind on small width

**Comment by matheusd** [comment]
Seems the create wallet button is now broken on the restore page

**Comment by vctt94** [comment]
fixed

**Pull request merged**
