### PR TITLE
Fixing overview

### PR DESCRIPTION
**Pull request by vctt94**
Fixing some details linnutee pointed at slack.

- Adding txHistory with no status (if not pending) at overview page
- Returning no ticket information on home recent transactions
- Fixing some chart style

### CODE REVIEW

**Comment by matheusd** [comment]
needs a rebase

**Comment by alexlyp** [comment]
lint-fix plz

**Comment by alexlyp** [comment]
Too much whitespace around the bottom and left of the graphs.

The recent transactions row does not match the design doc from @linnutee

**Comment by vctt94** [comment]
I believe now the transactions row are right.

Also, I found a bug, as we are using recentTransactions on selector, if we have many last transactions of only one kind (like only transactions or only tickets) the card does not show properly.
Here is an image: 
bugex

I changed recentTransactions for transactions and looks like it works, but I am not sure if this is the right approach.

**Comment by alexlyp** [comment]
Yah I'm going to open an issue and discussion with @matheusd on how to fix that problem.  Basically it needs to populate recentTickets a bit differently to make sure it has something to put there.

**Comment by alexlyp** [comment]
Can you cut the AM/PM and make it into 24H format for the time?

**Comment by vctt94** [comment]
Yeah, sure.

Should I change back for recentTransactions in here https://github.com/decred/decrediton/pull/1157/files#diff-a7298267586e8979aeb195bb3079d9d2R267 as well until we have a solution?

**Comment by alexlyp** [comment]
No that will goof up other things, I'll look into the fix for that today

**Comment by alexlyp** [comment]
I'm still seeing the recent transaction's dates not have enough room and then it causes them to expand the height of the row then causes the transactions to overflow off the bottom of the screen.  And the rows are no longer clickable to see tx details.

**Comment by alexlyp** [comment]
Also still seeing extra whitespace around the charts

**Comment by vctt94** [comment]
I removed the bottom white space. but I am not seeing this overflow, so I added a little padding on bottom so it fixes. Does it? 

Still need to remove the commas from the date. I am working on it.

**Pull request merged**
