### PR TITLE
trezor: Copy udev rules.

### LINKED ISSUE #3901: Trezor fixes (bundle bridge + udev rules)
As of this moment Decrediton relies on the user manually installing the [Trezor Bridge](https://data.trezor.io/bridge/latest/index.html) software before they can use their device.

- Decrediton should make use of whatever mechanism Trezor Suite uses to access the device, which likely means bundling all the necessary tools for Trezor to just work without the user needing to hunt down additional tools.
- It should also prompt the user and offer to automatically install the [Trezor udev rules](https://data.trezor.io/udev/51-trezor.rules).
- We may want to take inspiration from how [Trezor solved this](https://github.com/trezor/trezor-suite/pull/4133) for Trezor Suite.

Relevant Matrix discussions:

https://matrix.to/#/!MYLcxlwzxwViTaFPGo:decred.org/$dqHvqW7IXOhrxvJzViTFboXncwvgpd7qEKli_Q6ZE3M?via=decred.org&via=matrix.org

https://matrix.to/#/!xUNvyzkFgiMjhvPbIi:decred.org/$IIiIaoprWFJa_wm1vrMzClLWTJMTbT8Ab7kAdYsuTPc?via=decred.org&via=matrix.org&via=t2bot.io

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #3901

### CODE REVIEW

**Comment by JoeGruffins** [comment]
It seems like `electron-sudo` this needs the package https://www.nongnu.org/gksu/ installed, which isn't even offered on my distro. It should be on ubuntu. Trezor is using `pkexec` which should be only command line only. I need to try out their package again with no rules to see what it looks like.

**Comment by matheusd** [comment]
I'm pretty hesitant on this. 

First, it adds an additional dependency on the electron layer, which we should be trying to avoid at all costs (due to possible supply chain attacks). 

Second, adding sudo capabilities natively to the wallet seems unwise (imagine the cross section of a supply chain attack having access to the sudo abilities of the wallet, masking what is attempting to do with a standard wallet dialog).

I would be a bit less worried if this was isolated completely in a separate wallet process/layer (not sure if this is possible) and was only launched by an explicit user action to install the trezor udev rules (to avoid having this code possibly accessible to other parts of the app).

**Comment by JoeGruffins** [comment]
Yeah, the trezor suite download does not work for me. Stuck here forever:

image

@jzbz @matheusd 

Would just a popup with an explanation and a link to maybe https://trezor.io/learn/a/udev-rules be fine? We can also not use the link and include the rules and how to copy them.

**Comment by matheusd** [comment]
Showing a popup with instructions and a link for additional explanation seems fine to me (this is linux only after all).

**Comment by JoeGruffins** [comment]
Going to show instructions instead of doing it this way in a new pr.

**Pull request closed without merging**
