### PR TITLE
Improve see proposal comment button alignment

### LINKED ISSUE #2428: [redesign] Eligible tickets section in proposal details page
See screenshot:
image

**Update:** 
We ended up getting new design for the eligible tickets section, see comment below: https://github.com/decred/decrediton/issues/2428#issuecomment-606018117

### PR DESCRIPTION
**Pull request by amassarwi**
Closes #2428

### CODE REVIEW

**Comment by amassarwi** [comment]
Oh, missed the other usages!
I'll give a second shot and try make it work properly everywhere maybe ?

**Comment by vctt94** [comment]
Or that or you can add a specific class for the usage you want to. I am fine by either way

**Comment by amassarwi** [comment]
@vctt94 Updated mate

**Comment by alexlyp** [comment]
Waiting for further design input from @linnutee on #2428

**Comment by amassarwi** [comment]
Considering the new specs & the decision to try integrate pi-ui's at this stage this PR is outdated.
I've opened a draft PR https://github.com/decred/decrediton/pull/2457

**Pull request closed without merging**
