### PR TITLE
WIP: Tooltip spring

### PR DESCRIPTION
**Pull request by Jascha-Sundaresan**
Just for fun, I added a spring to the tooltip.

We can tweak the params of course.

### CODE REVIEW

**Comment by dajohi** [comment]
please rebase

**Comment by Jascha-Sundaresan** [comment]
I'm still playing around with this. I'll rebase it shortly.

**Comment by alexlyp** [comment]
yah it would be a nACK for me on the way it works and the usage of freactal.  but feel free to leave it open if you want to continue to fiddle

**Comment by alexlyp** [comment]
since this is a nACK from me and has been unattended for 3 months, closing.

**Pull request closed without merging**
