### PR TITLE
Responsive views: Launcher overview and Logs

### PR DESCRIPTION
**Pull request by bgptr**
closes (#2059) and (#2061)

### CODE REVIEW

**Comment by bgptr** [comment]
Thanks for the review.

- the overflow-x problem is a good catch, I didn't notice it. It's not always visible, just on certain page widths. I committed a fix for that.
- when clicking at the settings icon, how `logs` and `settings` should show up? 
Like this?
setttings_icon

The settings icon should disappear or it has a toggling mechanism?

**Comment by MariaPleshkova** [comment]
@bgptr you know, I just thought that no need in this icon at all. I mean we can leave them as they are on desktop and tablet views. There are only 2 items under settings icon so I guess they can fit perfectly in one line with the logo even on mobile screens. What do you think?

**Comment by bgptr** [comment]
@MariaPleshkova I like it. Thank you.

**Comment by bgptr** [comment]
I fixed your reviews comments. I changed the menu position from fixed to relative as you requested and changed the logo positioning too.

**Pull request merged**
