### PR TITLE
UI Improvements

### LINKED ISSUE #730: Dropdowns for type selection restyling
Update all dropdowns for various type selection to match designers prototype.

### PR DESCRIPTION
**Pull request by matheusd**
Fixes #730, #731, #732

### CODE REVIEW

**Comment by alexlyp** [comment]
Overall looks great.

Thoughts on what to do with the Tx Type label next to the dropdown?  I'm thinking we should just nuke it since I feel like the dropdown is more more clear on purpose currently.

**Comment by alexlyp** [comment]
Also I find the vertical padding for the transaction type options is a bit high, should a bit more wider and not as tall per option imo.

**Comment by matheusd** [comment]
Ok, I've made the improvements listed here and by @linnutee on the individual issues.

There are likely to be further issues after the designers get their hands on a built version and can play around, but this should be close to done.

**Comment by matheusd** [comment]
Latest push fixes the icon as specified in #734

**Comment by matheusd** [comment]
I've also fixed #757 now on my branch for this PR, but github is not showing the new commits. May be due to the fact that I had to rebase the work.

If this doesn't show up correctly, I'll close and open a new PR.

**Comment by alexlyp** [comment]
I'll be opening another issue that i noticed while testing this.  but this is good to go.

**Pull request merged**
