### PR TITLE
Add search limit for live tickets

### PR DESCRIPTION
**Pull request by vctt94**
A work torwards #2831.

I am not closing it, as I still think we can do more improvements on it

### CODE REVIEW

**Comment by matheusd** [comment]
Ok, this is definitely an improvement in sorting. And just to confirm: we're not supposed to show expired/missed tickets in the tickets status pane?

**Comment by vctt94** [comment]
No, right now it is only responsible for showing live and immature tickets, so we can show the fee status of the new vsp.

Missed/revoke tickets are still being showed on the `history tickets` tab. 

Not the best naming, but that's how it is being done right now

**Review by jholdstock — CHANGES_REQUESTED** [review]
This works as intended, only the previous `(ticket expiry + coinbase maturity)` blocks are being scanned now. This is a good improvement, but still does not fix most of the issues in #2831.

Issue related to this PR:

- The way progress percentage is calculated hasnt been updated, so it is still calculated down to block 0. This means the list finishes loading at around 7-8%.

**Comment by vctt94** [comment]
Right, but after it reaching the end of the search it will show like this, so I don't think this is a problem

image

**Comment by jholdstock** [comment]
Regardless, a progress indicator which runs from 0-8% is not helpful. It should either run from from 0-100%, or it should be removed.

**Comment by vctt94** [comment]
I am not really willing to change a lot this code piece at this point. 

I agree that it can be improved, but it would require a new selector and code changes which I think can be done for the next release

**Comment by alexlyp** [comment]
Yah let's just remove/hide the progress indicator for now until we have a chance to improve it later.

**Review by jholdstock — CHANGES_REQUESTED** [review]
So now the entire "Loading" page is gone, and the tab just remains blank until the "No tickets" message appears. 

With my comments above I was just referring to removing the Percentage. The ticket animation, the "Loading more tickets..." message, and the "Down to block XX..." message, can all be kept.
Screenshot from 2020-12-10 08-01-33

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
