### PR TITLE
spv: spv mode indicator on sidebar

### LINKED ISSUE #2640: Add SPV mode label
As suggested by @davecgh:

> I think it would be a good idea to make the mode (SPV versus Full) more prominent.  Maybe down next to the block height.  e.g. Latest Block: 478390 (SPV or Full Mode Icon).

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff closes #2640 by adding the SPV icon on "Latest Block" sidebar section.

Screen Shot 2020-09-11 at 10 31 06 AM

(on hover)
Screen Shot 2020-09-11 at 10 31 00 AM

### CODE REVIEW

**Review by vctt94 — COMMENTED** [review]
Thanks for this PR. I think it looks good, but can you also add it when the sidebar is reduced or in the bottom?

**Comment by victorgcramos** [comment]
So I think that we should use the label SPV instead of the icon. What do you think @vctt94

**Comment by alexlyp** [comment]
Hrm I think the icon with a tooltip should suffice for now.  We can tweak if people seem to be confused after release.

**Comment by victorgcramos** [comment]
IMO, on mobile view, adding the spv icon would pollute the current UI. Maybe we should go with the icon + tooltip for the full-width view, and use the label for collapsed views.

**Comment by vctt94** [comment]
Fine by me

**Comment by victorgcramos** [comment]
Collapsed view looks like this:
Screen Shot 2020-09-17 at 11 37 23 AM

**Review by vctt94 — APPROVED** [review]
LGTM

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
