### PR TITLE
electron: Update to 27.0.3.

### LINKED ISSUE #3921: Ledger: Broken on master.
master is currently 391d8a54e73b543eb8570705c0ff56d62aeca89c

Ledger needs WebUSB in order to work which is not supported by the current electron version. Please see the discussions in #3884

### PR DESCRIPTION
**Pull request by JoeGruffins**
closes #3921

### CODE REVIEW

**Comment by alexlyp** [comment]
@matheusd That was what I encountered as well.  I was able to narrow it down to something in https://github.com/electron/electron/releases/tag/v21.3.0 that was causing it to not work on Linux anymore.  Hence why I rolled back to 21.2.3.  Afaict that's the last working version of electron.  And the only change in there that could possibly have a difference is a Chromium update.

**Comment by matheusd** [comment]
While debugging I set the dex window to openDevTools and I get an error there. That may or may not be the issue. I'm retesting on master and then will test on 21.3.0 to see if that's the issue

**Comment by matheusd** [comment]
This is the error I get starting on electron 21.3.0 when opening the dex window (this is the console for the dex window, **not** the main decrediton window):

image

**Comment by matheusd** [comment]
I expect something in chromium broke a lib that the dex interface uses on linux.

**Comment by matheusd** [comment]
I believe this is the issue:

`navigator.languages`
  - on 21.2.3:  `['en-US']`
  - on 21.3.0: `['en-US', 'c']`
  
We'll probably need to check with the DEX UI ppl how to fix this

**Comment by JoeGruffins** [comment]
> On Windows the `rebuild-natives` call failed due to node-abi not supporting electron 27.0.3. I had to downgrade to 26.4.3 to rebuild native modules. DEX worked on that version.

@matheusd Shall I make this upgrade to 26.4.3? That also solves the main ledger issue.

**Comment by matheusd** [comment]
> @matheusd Shall I make this upgrade to 26.4.3? That also solves the main ledger issue.

Yes please. This should fix the windows build, though there's still the issue of the DEX UI failing on linux.

**Comment by alexlyp** [comment]
Closing this one in favor of another that includes the dcrdex fix as well.

**Pull request closed without merging**
