### PR TITLE
Responsive Settings and Transaction Details

### LINKED ISSUE #1951: Responsive views: Transaction Details
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/ffa08ee0-45e5-4daf-5fb5-3c51de25efd3-8991/
Specs: https://xd.adobe.com/spec/68180e46-60bf-4ad8-709e-9ad15191f137-1e29/

In tablet only scaling down the spacing. 

In mobile i've kept all the element sizes the same as much as possible. 
Top header area (with white background): in case there are more detail items, these should stack in a row and increase the header area height) 
Secondary header area (light grey): only change is rebroadcast icon being centrally aligned for consistency. 
Content area: I/O details are stacked top down and the arrow is also facing down accordingly. 
Raw transaction element is scaled down in width; repositioned slightly under the element title and copy to clipboard icon is also slightly repositioned.

### LINKED ISSUE #2000: Responsive views: Settings
Responsive views master issue: #1820

Preview: https://xd.adobe.com/view/2770aadf-642c-4936-6347-efd97b56a16d-5141/
Specs: https://xd.adobe.com/spec/d57694d8-4994-422e-5205-fdffd34564a4-a347/

Two content columns are stacked in top-down manner when scaling to smallest view.

### LINKED ISSUE #2201: [settings] Update private passphrase spacing
The spacing between the button and the word "Update" is a bit off.

### PR DESCRIPTION
**Pull request by bgptr**
This closes #1951, closes #2000, and closes #2201

### CODE REVIEW

**Comment by bgptr** [comment]
Thank you for the review.

Sorry for the multi-issue PR, I won't do that again.

I think on the screenshot there is no `transaction fee` because it's an incoming transaction.
The `to address` row is missing, but it's missing in the master branch too. 
Am I right or just looking for it in the wrong place?

Meanwhile, I find an issue with the header. It has a fixed height and it did not increase properly. Now it is corrected.

**Comment by vctt94** [comment]
Also https://github.com/decred/decrediton/issues/2222 made me realize that the save button is not showing at the screen in smaller width. Can you fix that, as well?

**Comment by bgptr** [comment]
I am on the `output addresses`. 

I think this PR already solve #2222. At least I can not reproduce it.

**Comment by vctt94** [comment]
Weird, here it doesn't show, look: 

image

**Comment by bgptr** [comment]
Maybe I messed up my git repo. Now I synced the PR. 
The header should be in the scrollable area.

image

**Comment by vctt94** [comment]
Yeah, I noticed. You brought some master's commits to your PR. Can you rebase it?

**Comment by bgptr** [comment]
I've rebased it and added the output addresses.

**Comment by vctt94** [comment]
Are you sure? Here it still does not show

image

**Comment by bgptr** [comment]
Please try it now.

**Comment by vctt94** [comment]
Thanks, it looks fine now. I have just one more comment. Can you edit this PR so the issues close when merging it?

When writing in topics like that, github doesn't close the issues when merging the PR.
To properly close you need to specify issue by issue.

From github documentation: `For example, This closes #34, closes #23, and closes example_user/example_repo#42 would close issues #34 and #23 in the same repository, and issue #42 in the "example_user/example_repo" repository.`

source: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords#closing-multiple-issues

**Comment by bgptr** [comment]
Sure. I edited it.

**Comment by alexlyp** [comment]
Please resolve these conflicts and then it should be good to go.

**Pull request merged**
