### PR TITLE
[actions] Improve close wallet action

### LINKED ISSUE #1551: Add close wallet action
Add an action (maybe in the main sidebar?) to close the current wallet, return to the wallet selection screen and allow the user to open or create a different wallet.

This might be slightly tricky as we need to close the dcrwallet process and all connections, and all the UI code assumes that once the wallet is loaded it won't change.

Might wanna hold off implementing this only after spv hits, since this will further change things.

### PR DESCRIPTION
**Pull request by matheusd**
Fix #1551 

This improves the close wallet action by cleaning up wallet state from redux, cancelling all outstanding streams and stopping the wallet, then returning to the wallet selection page.

Tested on spv and regular sync modes, but only in linux.

### CODE REVIEW

**Comment by vctt94** [comment]
Tested and seems to work fine. Good job

**Comment by alexlyp** [comment]
Seems to work pretty well.  Noticing the Open Wallet page coming up on subsequent loads briefly.  Otherwise gtg

**Comment by matheusd** [comment]
@alexlyp Which page exactly?

**Comment by alexlyp** [comment]
After I close the wallet and then select a new wallet to load, the Open Wallet page (asking for the public encryption passphrase) is shown briefly while the button for that is appears to be "loading/working".

**Comment by matheusd** [comment]
Weird, I never hit that. Did the previously open wallet require the public encryption passphrase?

**Comment by alexlyp** [comment]
No it was a default password.

Definitely not a huge issue and shouldn't block this PR, I can open an issue to address it since it's sort of out of scope of these changes.

**Comment by alexlyp** [comment]
Looks good.  I'll keep testing and take care of the open wallet flash if I keep seeing it.

**Pull request merged**
