### PR TITLE
[watch only] Watch only transaction

### LINKED ISSUE #1682: Allow watch only wallets to construct transactions
Maybe this could be done by changing the send button in the send page to a "construct" button that just shows the most recently constructed tx.

This would allow decrediton to produce a tx that could be saved and moved to a separate computer for signing.

### PR DESCRIPTION
**Pull request by vctt94**
closes #1682 

I need to rebase, so if can test in trezor mode, that would be great.

### CODE REVIEW

**Comment by matheusd** [comment]
Only small issue is that in trezor-enabled wallets, you shouldn't show the unsigned transaction, but rather continue with the signing flow (which should send the sign request to trezor).

You can manually set a wallet as using trezor (to test out the behavior, even if you can't sign it) by modifying the wallet's `config.json` (_not_ the global one) to have `trezor: true`.

**Comment by vctt94** [comment]
fixed

**Comment by matheusd** [comment]
I'm still seeing the raw constructed transaction on the trezor wallet, which is unnecessary.

**Comment by vctt94** [comment]
My bad. Removed it now.

One thing I noticed, is that when in trezor mode, the wallet seems to not turn it off, when switching between wallets.

**Comment by matheusd** [comment]
Yeah, I had noticed that bug earlier in regards to the sidebar. Fixed in #1876.

One last nit: transactions can be big and overflow the white area (eg):

screenshot_2018-12-07_11-59-42

**Comment by vctt94** [comment]
fixed

**Pull request merged**
