### PR TITLE
[constants] consistent file names.

### PR DESCRIPTION
**Pull request by amassarwi**
This changes couple of file names in `app/constants` dir to have consistent file names.
This commit updates all files to start with small letter.

### CODE REVIEW

**Comment by amassarwi** [comment]
tests failing 👀

**Review by matheusd — COMMENTED** [review]
I believe you need to rename the file `constants/Decrediton.js` to `constants/decrediton.js` as well.

**Comment by amassarwi** [comment]
@matheusd ughhh macos has case-insensitive filesystem, let me try to force the file name change on git.

**Comment by amassarwi** [comment]
should be good now

**Review by matheusd — APPROVED** [review]

**Comment by alexlyp** [comment]
quick conflict

**Comment by amassarwi** [comment]
@alexlyp updated

**Pull request merged**
