### PR TITLE
[launch] Return to daemon connection on error

### LINKED ISSUE #2621: [launch] After different network error decrediton goes to wrong state
After having a different network error (a mainnet daemon, connecting to a testnet decrediton, for example), decrediton goes to wallet selection, instead of going back to daemon connection

### PR DESCRIPTION
**Pull request by amassarwi**
Closes #2621

### CODE REVIEW

**Comment by amassarwi** [comment]
@vctt94 I was able to connect after changing to the right testnet running daemon.

**Review by vctt94 — COMMENTED** [review]
The issue described was fixed but we found another issue which amass is fixing

**Comment by amassarwi** [comment]
@vctt94 added config files path to network mismatch error's action suggestion:
image

**Review by vctt94 — APPROVED** [review]
Great! Thanks for that amass

**Review by alexlyp — APPROVED** [review]

**Pull request merged**
