### PR TITLE
Fix a few lint issues that got in.

### LINKED ISSUE #168: lint
Some lint issues slipped in, need fixing.

### PR DESCRIPTION
**Pull request by jcvernaleo**
Closes #168

### CODE REVIEW

**Comment by jolan** [comment]
Actually lint-fix did that and this PR just brings it back:

Will check versions/configs/etc.

```
jolan@deski7:~/code/decrediton$ npm run lint

> decrediton@0.7.0 lint /home/jolan/code/decrediton
> eslint --ignore-path .eslintignore *.js app


/home/jolan/code/decrediton/webpack.config.js
  15:5  error  Expected indentation of 6 spaces but found 4  indent
  16:7  error  Expected indentation of 8 spaces but found 6  indent
  17:7  error  Expected indentation of 8 spaces but found 6  indent
  21:5  error  Expected indentation of 6 spaces but found 4  indent
  23:5  error  Expected indentation of 6 spaces but found 4  indent
  24:7  error  Expected indentation of 8 spaces but found 6  indent
  25:7  error  Expected indentation of 8 spaces but found 6  indent
  29:5  error  Expected indentation of 6 spaces but found 4  indent

✖ 8 problems (8 errors, 0 warnings)
```

**Comment by jcvernaleo** [comment]
That is very weird.  Do you have a local eslint config maybe?  I don't think that I have one.

**Comment by jcvernaleo** [comment]
Just to compare, I have:
```
jcv@triforce decrediton $ node -v
v6.5.0
jcv@triforce decrediton $ ./node_modules/.bin/eslint -v
v3.12.2
```

**Comment by jolan** [comment]
I rm'd various things in .gitignore and did a fresh install/build and now my environment matches.

**Pull request merged**
