### PR TITLE
[tickets] Add SetVspdVoteChoice request

### LINKED ISSUE #3197: Not possible to change from default 'Abstain' voting preference in Consensus tab
Can't change the preference from Abstain to Yes or No in Decrediton 1.6. Clicking the Update Preference button does nothing.

 
Screen Shot 2021-02-03 at 9 23 55 AM

I am in macOS 11.1

Screen Shot 2021-02-03 at 9 35 20 AM

### PR DESCRIPTION
**Pull request by alexlyp**
~Requires https://github.com/decred/dcrwallet/pull/1981~

Close #3197 

Now on update vote preference the wallet is sent a SetVspdVoteChoice request for any currently available vspd.

### CODE REVIEW

**Review by amassarwi — APPROVED** [review]
Code LGTM

**Review by vctt94 — COMMENTED** [review]
If entering a wrong password, it gives me two notifications, one with success and one failed.

image

It also gives two notifications when success, maybe we can explicity it is updating legacy vsp and new ones, so we can try to avoid confusion? Other problem is the time between the two notifications can be long, and there is no feedback that something is happening, so I think it might be confusing with the first notification

image

Otherwise it looks good.

Good job on this PR

**Review by vctt94 — COMMENTED** [review]
If entering a wrong passphrase, the button keeps show loading and I can not retry

image

**Review by vctt94 — APPROVED** [review]
tACK

**Pull request merged**
