### PR TITLE
Disable "About Decrediton" modal duplicate

### PR DESCRIPTION
**Pull request by szpasztor**
Resolves https://github.com/decred/decrediton/issues/1651

### CODE REVIEW

**Comment by szpasztor** [comment]
General method: use electron's `icpRenderer` to send events from main to render process and handle the click in the latter. 

Need help on how to proceed though. `AboutModal` should get its `show` prop from the newly added `aboutModalVisible` in state. How can I determine the connections between connectors and components? In this example, which connector should I use? Already tried searching for a given connector's usages but since their names are short, there are thousands of string matches.

**Comment by matheusd** [comment]
This one is going to be a bit tricky.

I think you'll need to create the `<AboutModal` component directly in the `render()` method of the App container, based on whether the state you created is set or not. And you'll need to hook the `onCancelModal` so that the state is reset and the modal hidden.

**Comment by alexlyp** [comment]
Any updates on this @szpasztor ?

**Comment by szpasztor** [comment]
Rendering the `AboutModal` directly in the App container led to problems related to `ReactDOM.createPortal` receiving `null` as its domNode for some reason (might be related to the target domNode having the same parent dom element as the component); didn't have success after hours of debugging. I'll continue with a partial rewrite of AboutModal without using a portal.

**Comment by szpasztor** [comment]
Update: found a solution by rendering two modals: one for the macOS navbar click and one for all other types of invocations (ie. macOS AboutModal button press and everything on Windows and Linux). The app verifies that at most one of the two kinds is rendered at any given time so there's no overlap. 

Tested on macOS 10.14.1. Not tested on Linux nor Windows. 

Ready for review @matheusd

**Comment by szpasztor** [comment]
Here's the behavior I verified to be working: 
- Clicking navbar/about  (wallet select page or loaded app) => about modal shown
- Clicking decrediton's existing about modal button (wallet select page) => about modal shown
- Clicking navbar/about again without closing about modal first => nothing happens
- Clicking navbar/about with any modal open => nothing happens
- About modal can be exited in any of the above

Can we get someone to test for regressions on Windows?

**Pull request merged**
