### PR TITLE
[politeia] initial version

### PR DESCRIPTION
**Pull request by matheusd**
Requires #1242.
Part of #1244.

Please notice the big WIP tag on the title. 

Status:

- [x] Wait for #1242 merge to decrediton master
- [x] Wait for plugin branch of politeia to become master
- [x] Wait for testnet deployment of politeia
- [x] Review and fix stuff
- [x] Remove all instrumentation

### CODE REVIEW

**Comment by matheusd** [comment]
Ready for final review.

**Comment by alexlyp** [comment]
Looks great!

I asked the guys to add a new proposal up for vote so I can test that part.

Everything looks good so far except buttons to All Proposals and Create a Proposal both go to: https://test-proposals.decred.orgundefined

So likes like something is getting appended strangely there.

**Comment by alexlyp** [comment]
Great work!

Really the only thing I can see that is an issue is the empty Voting Deadline line in Vote Ended listed proposals.  I'd either hide that line entirely or show it as normal since it might be good information for people to see when the vote actually took place etc.

**Comment by matheusd** [comment]
I've hidden the voting deadline for non-voting proposals, since that information is not available for them.

**Pull request merged**
