### PR TITLE
Refine purchase ticket form.

### PR DESCRIPTION
**Pull request by jholdstock**
- Only show "i" information icon on the legacy form.
- Splt "Staking Overview" and "Purchase Ticket" panels. Give them their own headers.
- Change "From Account" to "Account" and "From VSP" to "VSP". This matches the old form.
- Update "Is Legacy" to "Use Legacy VSP" and provide a tooltip for more information.
- Give Auto ticket buyer the same title style regardless of legacy/new.

Fixes most of #2803 - I will update that issue with the outstanding issues once this PR is merged.

### CODE REVIEW

**Review by victorgcramos — APPROVED** [review]
Really good improvements! Looking much better! Just a quick preview of the improved view in comparison to the old one:

**Improved view**
Screen Shot 2020-11-03 at 3 36 03 PM

**Current view**
Screen Shot 2020-11-03 at 3 36 31 PM

**Review by vctt94 — COMMENTED** [review]
I think this is a good improvement, but I think it can be misleading with privacy ticket purchase. Here how it looks on this PR:

image

That's the reason we didn't use subtitlte on this view, so we can better "separate" them, into categories. So now the `privacy settings` looks weird. 

What do you think?

Also I think we can add a vertical margin between VSP and Account.

**Comment by jholdstock** [comment]
Ah, I hadnt seen these privacy options on the ticket purchase tab before.

Aren't these options only relevant for the auto-buyer? Do they have any effect when making single, manual ticket purchases?

**Comment by vctt94** [comment]
No, they are relevant for manual purchase, as well. For them to showing you just need to configure privacy

**Review by vctt94 — COMMENTED** [review]
Thanks! This is looking good. 
I have a couple small nits

Can you put the checkbox inside the tooltip, so it shows when hovering it. Also can you make the mouse pointer when on the checkbox. 

image

**Comment by jholdstock** [comment]
Now using pi-ui checkboxes, which works much nicer with the tooltip. Tooltip and mouse pointer now cover both the checkbox and the label.

**Review by vctt94 — APPROVED** [review]
Thanks, looking much better now! 

LGTM

**Pull request merged**
