### PR TITLE
[governance] Eligible tickets component & TxHistory css module

### LINKED ISSUE #2428: [redesign] Eligible tickets section in proposal details page
See screenshot:
image

**Update:** 
We ended up getting new design for the eligible tickets section, see comment below: https://github.com/decred/decrediton/issues/2428#issuecomment-606018117

### PR DESCRIPTION
**Pull request by amassarwi**
This diff adds the recently designed eligible tickets table (#2428) and it includes the following changes:
 - Add new `EligibleTickets` component to proposal details helpers.
 - Expand `TxHistory` to support new row type and used in `EligibleTickets` to display eligible tickets rows.
 - Migrate `TxHistory.less` and parts of `HistoryPage.less` to a css module - good example of a nested, mishmashed, hard to predect styling, which is why we are moving to css modules.
 - Expand `getProposalDetails` action to fetch ticket & transaction information (status, spender, ...) for all eligible tickets hashes, using gprc calls and appended the normalized transactions to stakeTransactions redux obj which is needed to be able to show the transaction details page when user clicks on a eligible ticket row.
- Improve proposal body displaying to better match the provided design specs.

Result:
image

Collapsed mode & improved proposal body:
image

---

Closes #2428

### CODE REVIEW

**Comment by amassarwi** [comment]
I would like to improve the following by making the component not expandable & maybe event hiding the arrow:
image

**Comment by vctt94** [comment]
sounds good

**Comment by amassarwi** [comment]
>  1. In some cases tickets price & account name aren't displayed

Fixed.

**Comment by amassarwi** [comment]
> I would like to improve the *0 tickets* case by making the component not expandable & maybe event hiding the arrow

image

@vctt94 done mate, was pretty straight forward with the css module in place.
I see proposal details in general need some responsiveness punishment I can do work on that next anyway and try improve the page in general for smaller screens.

**Comment by amassarwi** [comment]
>  Purchased column isn't consistent, according to the design specs it's enough to show only date so I will delete the time

Fixed.
image

**Comment by alexlyp** [comment]
Needs a quick conflict resolution.

**Comment by amassarwi** [comment]
@alexlyp ✅

**Pull request merged**
