### PR TITLE
[pi-ui] Integrate Tooltip component

### LINKED ISSUE #2512: [pi-ui] Integrate Tooltip & match style with current Tooltip
pi-ui has a Tooltip component which can replace `shared/tooltip` we are currently using.

### PR DESCRIPTION
**Pull request by amassarwi**
This diff ditch the `Tooltip` component from `components/shared` and replaces it with the one
we have in `pi-ui`.

Closes #2512

### CODE REVIEW

**Comment by amassarwi** [comment]
Wot ? looking

**Comment by vctt94** [comment]
Another place, the icon showing the mixer is running

image

I didn't go through all of them, but it would be good if the pi-ui's tooltip could check for extremities and make a offset, so that won't happen

**Comment by amassarwi** [comment]
Closed accidentally

**Comment by vctt94** [comment]
needs rebase

**Comment by alexlyp** [comment]
@amassarwi would like to get this guy in finally if you are able to fix the conflicts, may be faster to just start fresh.

**Comment by amassarwi** [comment]
To be continued on https://github.com/decred/decrediton/pull/3196.

**Pull request closed without merging**
